# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_API, ROLE_EDITOR]
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username        # fos_user.user_provider.username_email does not seem to work (OAuth-spec related ("username + password") ?)
    firewalls:
        oauth_token:                                   # Everyone can access the access token URL.
            pattern: ^/oauth/v2/token
            security: false
        api_doc:
            pattern: ^/api/doc
            anonymous: true
            stateless: true
        new_client:
            pattern: ^/api/user/new/client
            anonymous: true
            stateless: true
        access_token:
            pattern: ^/api/user/access/token
            anonymous: true
            stateless: true
        refresh_token:
            pattern: ^/api/user/refresh/token
            anonymous: true
            stateless: true
        request_password_email:
            pattern: ^/api/user/resetting/request/email
            anonymous: true
            stateless: true
        check_email:
            pattern: ^/api/user/resetting/check/email
            anonymous: true
            stateless: true
        register:
            pattern: ^/api/user/register
            anonymous: true
            stateless: true

        api:
            pattern: ^/api                             # All api URLs are protected
            fos_oauth: true                            # OAuth2 protected resource
            stateless: true                            # Do no set session cookies
            anonymous: false                           # Anonymous access is not allowed

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: homepage
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider
            logout:
                path: fos_user_security_logout
                target: homepage
            anonymous:    true
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/users/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/users/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
