parameters:
    # This parameter defines the codes of the locales (languages) enabled in the application
    # app_locales: en|fr|de|es|cs|nl|ru|uk|ro|pt_BR|pl|it|ja|id|ca|sl
    app_locales: en|fr|hi

# Assetic Configuration
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
nelmio_api_doc: ~

fos_rest:
    disable_csrf_role: ROLE_API
    routing_loader:
        default_format: json                            # All responses should be JSON formated
        include_format: false                           # We do not include format in request, so that all responses
    exception:
        enabled: true
        exception_controller: 'ApiBundle\Controller\ApiExceptionController::showAction'                                                        # will eventually be JSON formated
    versioning:
        enabled: true
        resolvers:
            query: true # e.g. Query parameter: /users?version=1.0
            custom_header: true # X-Accept-Version header: 1.0
        guessing_order:
            - query
            - custom_header
    format_listener:
        enabled: true
        rules:
            # setting fallback_format to false means that instead of considering the next rule in case of a priority mismatch, a 406 will be caused
            - { path: '^/image', priorities: ['jpeg', 'gif'], fallback_format: false, prefer_extension: true }
            # setting fallback_format to null means that in case of a priority mismatch the next rule will be considered
            - { path: '^/admin', methods: ['GET', 'POST'], priorities: ['xml', 'html'], fallback_format: ~, prefer_extension: false }
            # you can specifically target the exception controller
            - { path: '^/api', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: false }
            # setting a priority to */* basically means any format will be matched
            - { path: '^/', priorities: ['text/html', '*/*'], fallback_format: html, prefer_extension: true }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: ApiBundle\Entity\User

fos_oauth_server:
    db_driver:           orm
    client_class:        ApiBundle\Entity\Client
    access_token_class:  ApiBundle\Entity\AccessToken
    refresh_token_class: ApiBundle\Entity\RefreshToken
    auth_code_class:     ApiBundle\Entity\AuthCode
    service:
        user_provider: fos_user.user_manager             # This property will be used when valid credentials are given to load the user upon access token creation
        options:
            supported_scopes: USER API
monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        console:
            type:   console
            channels: [!event, !doctrine]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info
